# Front end container
FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy everything except node_modules (.dockerignore)
COPY . .
RUN npm run build

CMD ["npm", "start"]
EXPOSE 3000
