# Back end container
FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install -r requirements.txt

COPY . .
EXPOSE 8000

# Commenting this out to put it in the compose file instead possibly
# RUN ["python", "-m", "backend.SQL_UTIL.init_db"]

CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000"]
